
// Generated by https://quicktype.io

import { DecimalPipe } from "@angular/common";

    export interface Devshop {
        nombre_prod:   string;
        precio:        number;
        cod_coleccion: number;
        thema_imagen:  ThemaImagen;
        collecion:     string;
        arte:          Arte;
        tipo_prod:     string;
        color:         Color;
        talla:         string[];
        descripcion:   Descripcion;
    }
    

    

    export interface Arte {
        logotipo:         string;
        logotipo_bordado: string;
        mascota:          string;
    }
    
    export interface Color {
        dark:  Dark[];
        ligth: Dark[];
    }
    
    export interface Dark {
        nombre_color: string;
        image:        string;
    }
    
    export interface ThemaImagen {
        claro:  string;
        oscuro: string;
    }
    export interface Descripcion {
        detalle:     string;
        detalleprod: string[];
    }
    // Colecion de productos


    export interface Coleccion {
        cod_coleccion: number;
        nombre: string;
        image_url: string;
      }
      


  export interface ProdColeccion {
    nombre_prod:  string;
    precio:       number;
    thema_imagen: ThemaImagen;
    collecion:    string;
}

export interface ThemaImagen {
    claro:  string;
    oscuro: string;
}
// Interface de producto de carrito  de compra
export interface ProductoCard{
    producto :string;
    nombre_prod:string;
    imgColor:string;
    coloProd:string;
    tamaño:string;
    cantidad:number;
    precio: number;
}